# Automatically label Pull Requests according to the rules provided in config/label-pr.yaml 
name: 'Auto Label Pull Requests'
# Trigger the workflow on pull request events
on: [pull_request]
jobs:
  label:
    runs-on: ubuntu-18.04
    steps:
      # We need to checkout the repository to access the configured file (.github/label-pr.yml)
      - uses: actions/checkout@v2
      - name: Labeler
        uses: docker://decathlon/pull-request-labeler-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The path for the configuration files.
          CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/workflows/config/label-pr.yml
